#!/bin/sh

country=$1

if [ -z "$country" ] ; then echo "please enter country (US, CN, DE, FR)"; exit 1; fi;
wget -O - -q http://www.proxynova.com/proxy_list.txt?country=$country |tail -n 100  | xargs -L 1 sh -c 'wget -T 3 -t0 -e http-proxy=$1 google.com -O /dev/null -q --timeout=5 --connect-timeout=5 && echo $1 &' argv0
